name: .NET

on:
  push:
    branches: [ dev-p1 ]
  pull_request:
    branches: [ dev-p1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./LTS.Solution/LTS.Solution/LTS.Solution.sln
    - name: Build
      run: dotnet build ./LTS.Solution/LTS.Solution/LTS.Solution.sln
    - name: Test
      run: dotnet test ./LTS.Solution/LTS.Solution/LTS.Solution.sln
